version: '3.8'

services:
  postgres:
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=kufar-bot
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/kufar-bot
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/kufar-bot

volumes:
  postgres_data: